"""Alembic's entry point, wired to the application's own settings and metadata.

Three decisions, each of which prevents something specific.

**The URL comes from `config.get_settings()` and is passed through
`store.engine.normalise_database_url`.** Not from `alembic.ini`, which is committed and must never
carry a credential, and not from a second reader of the same environment variable. A migration run
against a different database from the one the application opens is the failure this removes, and it
is a failure that looks like a missing table at runtime rather than like a configuration mistake.
The normalisation matters here more than anywhere: `alembic upgrade head` is usually the *first*
command run against a managed database, so a `postgres://` URL from Render fails here first, and it
should fail with a message about a URL scheme.

**`target_metadata` is `store.schema.METADATA`.** Autogenerate is therefore comparing the database
against the same `MetaData` that `create_schema` builds from, so a drift between the shipped
migration and the ORM definition shows up as a non-empty autogenerated revision rather than as a
query against a column that does not exist.

**`compare_type` is on.** Alembic's default ignores column type changes, which is a reasonable
default for a schema of strings and integers and a bad one here: the vector column's width is the
embedding policy's dimension count, and a policy change that widened it while the column stayed at
384 would be invisible to autogenerate and would then raise once per row at insert time.

The extension statement lives in the first revision rather than here. Creating it from `env.py`
would mean an offline `--sql` run emitted a script that silently assumed the extension already
existed — and an offline script handed to a change-management process is precisely the artefact that
has to be complete.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine
from sqlalchemy.pool import NullPool

from warranty_claim_recovery.config import get_settings
from warranty_claim_recovery.store.engine import normalise_database_url
from warranty_claim_recovery.store.schema import METADATA

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = METADATA


def database_url() -> str:
    """The URL Alembic connects with: the command line if given, otherwise the application's.

    `-x url=...` is honoured so that a test can migrate a throwaway database without mutating the
    environment of the process it runs in. Mutating `os.environ` would be visible to every other
    test in the session, and `get_settings` is `lru_cache`d, so the mutation would not even take
    effect reliably — a combination that produces a test which passes or fails depending on
    collection order.
    """
    overrides = context.get_x_argument(as_dictionary=True)
    raw = overrides.get("url") or get_settings().database_url
    return normalise_database_url(raw)


def run_migrations_offline() -> None:
    """Emit SQL without a connection, for a reviewer or a change-managed deployment."""
    context.configure(
        url=database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run against a live database, in one transaction.

    `create_engine` with `NullPool` rather than `store.engine.build_engine`: a migration opens one
    connection, uses it once and exits, so the pool that `build_engine` configures for a long-lived
    worker is the wrong shape here. A pooled engine would hold connections open past the end of the
    process on a provider that counts them, which on a free tier is a small and self-inflicted
    outage. The URL still goes through the same normalisation, which is the part that has to be
    shared.
    """
    engine = create_engine(database_url(), poolclass=NullPool)
    try:
        with engine.connect() as connection:
            context.configure(
                connection=connection,
                target_metadata=target_metadata,
                compare_type=True,
            )
            with context.begin_transaction():
                context.run_migrations()
    finally:
        engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
